# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_kmeans')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_kmeans')
    _kmeans = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_kmeans', [dirname(__file__)])
        except ImportError:
            import _kmeans
            return _kmeans
        if fp is not None:
            try:
                _mod = imp.load_module('_kmeans', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _kmeans = swig_import_helper()
    del swig_import_helper
else:
    import _kmeans
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class Cluster(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cluster, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cluster, name)
    __repr__ = _swig_repr

    def __init__(self, data, rows, columns):
        this = _kmeans.new_Cluster(data, rows, columns)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def AddPoint(self, row):
        return _kmeans.Cluster_AddPoint(self, row)

    def CalcCentroid(self):
        return _kmeans.Cluster_CalcCentroid(self)

    def MinkowskiDist(self, d, n):
        return _kmeans.Cluster_MinkowskiDist(self, d, n)

    def PrintCentroid(self):
        return _kmeans.Cluster_PrintCentroid(self)

    def ResetPoints(self):
        return _kmeans.Cluster_ResetPoints(self)

    def GetNumAttrs(self):
        return _kmeans.Cluster_GetNumAttrs(self)

    def GetCentroid(self):
        return _kmeans.Cluster_GetCentroid(self)
    __swig_destroy__ = _kmeans.delete_Cluster
    __del__ = lambda self: None
Cluster_swigregister = _kmeans.Cluster_swigregister
Cluster_swigregister(Cluster)

class KMeans(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, KMeans, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, KMeans, name)
    __repr__ = _swig_repr

    def __init__(self, n_clusters=8, max_iter=300, random_state=-1):
        this = _kmeans.new_KMeans(n_clusters, max_iter, random_state)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def fit(self, invec):
        return _kmeans.KMeans_fit(self, invec)

    def predict(self, row):
        return _kmeans.KMeans_predict(self, row)

    def GetClusters(self, arr):
        return _kmeans.KMeans_GetClusters(self, arr)
    __swig_destroy__ = _kmeans.delete_KMeans
    __del__ = lambda self: None
KMeans_swigregister = _kmeans.KMeans_swigregister
KMeans_swigregister(KMeans)

# This file is compatible with both classic and new-style classes.


